import 'reflect-metadata';
import {
  type ComputedContext,
  FilterModule,
  FilterRunner,
  Filterable,
} from '@dudousxd/nestjs-filter';
import { Collection, MikroORM } from '@mikro-orm/core';
import {
  Entity,
  ManyToOne,
  OneToMany,
  PrimaryKey,
  Property,
  ReflectMetadataProvider,
} from '@mikro-orm/decorators/legacy';
import { MikroOrmModule } from '@mikro-orm/nestjs';
import { SqliteDriver } from '@mikro-orm/sqlite';
import { Injectable } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { afterEach, describe, expect, it } from 'vitest';
import { MikroOrmFilter } from '../src/mikro-orm-filter.js';
import { MikroOrmFilterModule } from '../src/module.js';

// ─── Entities ───────────────────────────────────────────────────────────────────

@Entity({ tableName: 'authors' })
class Author {
  @PrimaryKey()
  id!: number;

  @Property()
  name!: string;

  @OneToMany(
    () => Book,
    (book) => book.author,
  )
  books = new Collection<Book>(this);
}

@Entity({ tableName: 'books' })
class Book {
  @PrimaryKey()
  id!: number;

  @Property()
  title!: string;

  @ManyToOne(() => Author)
  author!: Author;
}

// ─── Filters ────────────────────────────────────────────────────────────────────

// `booksCount` is a computed/virtual field: a correlated subquery counting each
// author's books. `{alias}` is substituted at query-build time with the root
// entity alias MikroORM assigned (autogenerated, e.g. `a0`) so the subquery
// correlates to the outer row. Not a real column — filterable/sortable via the
// dev-provided expression only.
@Injectable()
@Filterable({
  entity: Author,
  autoFields: true,
  computed: {
    booksCount: '(SELECT COUNT(*) FROM books WHERE books.author_id = {alias}.id)',
  },
})
class AuthorFilter extends MikroOrmFilter<Author> {}

// A function-source computed field: same correlated subquery as `AuthorFilter`,
// but built from the real build-time alias handed to the callback rather than a
// `{alias}` string token.
@Injectable()
@Filterable({
  entity: Author,
  computed: {
    booksCount: ({ alias }: ComputedContext) =>
      `(SELECT COUNT(*) FROM books WHERE books.author_id = ${alias}.id)`,
  },
})
class AuthorFilterFn extends MikroOrmFilter<Author> {}

// ─── Test Suite ─────────────────────────────────────────────────────────────────

describe('MikroORM computed / virtual fields', () => {
  let orm: MikroORM;
  let runner: FilterRunner;

  async function createModule() {
    const mod = await Test.createTestingModule({
      imports: [
        MikroOrmModule.forRoot({
          driver: SqliteDriver,
          dbName: ':memory:',
          entities: [Author, Book],
          allowGlobalContext: true,
          metadataProvider: ReflectMetadataProvider,
        }),
        FilterModule.forRoot({ validation: 'off' }),
        MikroOrmFilterModule.forRoot(),
        FilterModule.forFeature([AuthorFilter, AuthorFilterFn]),
      ],
    }).compile();

    orm = mod.get(MikroORM);
    runner = mod.get(FilterRunner);
    await orm.schema.create();
    return mod;
  }

  // Ada → 3 books, Alan → 1 book, Grace → 0 books. Insertion order (Alan, Ada,
  // Grace) deliberately matches neither the asc nor the desc expected order, so
  // both sort tests fail loudly if the ORDER BY is dropped — rather than passing
  // on the default rowid order.
  async function seed() {
    const em = orm.em.fork();
    const alan = em.create(Author, { name: 'Alan' });
    const ada = em.create(Author, { name: 'Ada' });
    const grace = em.create(Author, { name: 'Grace' });
    em.persist([alan, ada, grace]);
    em.create(Book, { title: 'Notes A', author: ada });
    em.create(Book, { title: 'Notes B', author: ada });
    em.create(Book, { title: 'Notes C', author: ada });
    em.create(Book, { title: 'Solo', author: alan });
    await em.flush();
  }

  afterEach(async () => {
    if (orm) await orm.close(true);
  });

  it('sorts by a computed field ascending', async () => {
    const mod = await createModule();
    await seed();
    const qb = orm.em.fork().createQueryBuilder(Author);
    await runner.apply(AuthorFilter, { filter: {}, sort: 'booksCount' }, qb);
    const rows = await qb.getResultList();
    // 0, 1, 3 → Grace, Alan, Ada
    expect(rows.map((r) => r.name)).toEqual(['Grace', 'Alan', 'Ada']);
    await mod.close();
  });

  it('sorts by a computed field descending', async () => {
    const mod = await createModule();
    await seed();
    const qb = orm.em.fork().createQueryBuilder(Author);
    await runner.apply(AuthorFilter, { filter: {}, sort: '-booksCount' }, qb);
    const rows = await qb.getResultList();
    expect(rows.map((r) => r.name)).toEqual(['Ada', 'Alan', 'Grace']);
    await mod.close();
  });

  it('computed sort composes with a real-column sort, preserving order', async () => {
    const mod = await createModule();
    await seed();
    const qb = orm.em.fork().createQueryBuilder(Author);
    // Computed sort FIRST, then a real column. The real-column apply must not
    // clobber the computed ORDER BY that precedes it.
    await runner.apply(AuthorFilter, { filter: {}, sort: '-booksCount,name' }, qb);
    const sql = qb.getFormattedQuery().toLowerCase();
    const orderIdx = sql.indexOf('order by');
    expect(orderIdx).toBeGreaterThan(-1);
    const exprIdx = sql.indexOf('select count(*)', orderIdx);
    const nameIdx = sql.indexOf('`name`', orderIdx);
    // Both survive, computed first (request order preserved).
    expect(exprIdx).toBeGreaterThan(orderIdx);
    expect(nameIdx).toBeGreaterThan(exprIdx);
    await mod.close();
  });

  it('filters by a computed field (gt)', async () => {
    const mod = await createModule();
    await seed();
    const qb = orm.em.fork().createQueryBuilder(Author);
    await runner.apply(AuthorFilter, { filter: { booksCount: { gt: 1 } } }, qb);
    const rows = await qb.getResultList();
    // Only Ada has more than 1 book.
    expect(rows.map((r) => r.name)).toEqual(['Ada']);
    await mod.close();
  });

  it('parameterizes the client value (no SQL injection via the value)', async () => {
    const mod = await createModule();
    await seed();
    const qb = orm.em.fork().createQueryBuilder(Author);
    await runner.apply(AuthorFilter, { filter: { booksCount: { equals: 0 } } }, qb);
    const [sql, params] = [qb.getQuery(), qb.getParams()];
    // The dev expression is inlined; the client value is bound as a parameter.
    expect(sql).toContain('author_id');
    expect(params).toContain(0);
    const rows = await qb.getResultList();
    expect(rows.map((r) => r.name)).toEqual(['Grace']);
    await mod.close();
  });

  it('sorts by a function-source computed field', async () => {
    const mod = await createModule();
    await seed();
    const qb = orm.em.fork().createQueryBuilder(Author);
    await runner.apply(AuthorFilterFn, { filter: {}, sort: 'booksCount' }, qb);
    const rows = await qb.getResultList();
    // 0, 1, 3 → Grace, Alan, Ada
    expect(rows.map((r) => r.name)).toEqual(['Grace', 'Alan', 'Ada']);
    await mod.close();
  });
});
